# - name: Create backups directory
#   file:
#     path: /home/deploy/var/www/{{app_name}}/shared/backups
#     state: directory
#     owner: deploy
#     mode: 0755

# - name: Upload backup script
#   template:
#     src: templates/backup.sh
#     dest: /home/deploy/var/www/{{ app_name }}/shared/backup.sh

# - name: Upload cleaning script
#   template:
#     src: templates/remove_old_backups.sh
#     dest: /home/deploy/var/www/{{ app_name }}/shared/remove_old_backups.sh

# - name: Setup cron task for daily backups
#   cron:
#     name: "{{ app_name }} db daily backup to /home/deploy/var/www/{{ app_name }}/shared/backups/"
#     special_time: daily
#     job: "/home/deploy/var/www/{{ app_name }}/shared/backup.sh"

# - name: Setup cron task for removing 8 days old backups
#   cron:
#     name: "Remove older than week {{ app_name }} backups"
#     special_time: daily
#     job: "/home/deploy/var/www/{{ app_name }}/shared/remove_old_backups.sh"

- name: Install backup gem
  become: yes
  shell: "gem install backup"

- name: Install yandex-disk gem
  become: yes
  shell: "gem install yandex-disk"

- name: Create backups directory
  file:
    path: /home/deploy/var/www/{{ app_name }}/backups
    state: directory
    owner: deploy
    mode: 0755

- name: Create backups directory
  file:
    path: /home/deploy/var/www/{{ app_name }}/backups/models
    state: directory
    owner: deploy
    mode: 0755

- name: Upload backups config
  template:
    src: templates/config.rb
    dest: /home/deploy/var/www/{{ app_name }}/backups/config.rb

- name: Upload backups model
  template:
    src: templates/backup_model.rb
    dest: /home/deploy/var/www/{{ app_name }}/backups/models/{{ app_name }}.rb
