- name: Install backup gem
  become: yes
  shell: "gem install {{ item }}"
  with_items:
    - backup

- name: Create backups directory
  file:
    path: /home/deploy/var/www/{{ app_name }}/backups
    state: directory
    owner: deploy
    mode: 0755

- name: Create backups directory
  file:
    path: /home/deploy/var/www/{{ app_name }}/backups/models
    state: directory
    owner: deploy
    mode: 0755

- name: Upload backups config
  template:
    src: templates/config.rb
    dest: /home/deploy/var/www/{{ app_name }}/backups/config.rb

- name: Upload backups model
  template:
    src: templates/backup_model.rb
    dest: /home/deploy/var/www/{{ app_name }}/backups/models/{{ app_name }}.rb

- name: Setup cron task for daily backups
  cron:
    special_time: daily
    name: "{{ app_name }} db daily backup"
    job: "/usr/local/rvm/wrappers/ruby-{{ ruby_version }}/backup perform -t {{ app_name }} --config-file /home/deploy/var/www/{{ app_name }}/backups/config.rb"
