---
- name: Create deploy user
  user: name=deploy
        state=present
        groups="sudo"
        password={{ password }}
        shell=/bin/zsh
- name: Give deploy user sudo rights
  lineinfile: dest=/etc/sudoers
              state=present
              regexp='^deploy ALL\='
              line='deploy ALL=(ALL) NOPASSWD:ALL'
              validate='visudo -cf %s'
- name: Setup authorized key for deploy user
  authorized_key: user=deploy key="{{ lookup('file', '/Users/frey/.ssh/id_rsa.pub') }}"
